travis:
  secure:
    BINSTAR_TOKEN: McrWyq33wE782xgR1GwL2r5bNcRlILRHGe53WQx6N54oIDioQnYJxvjTO7leUSPjLh/32yDOsbJrDznQ+trmmN5VReksth5hgBnZOLz/zktwLnQBIckepncMFwMWSQ+huMtBdRLVQQdSzrm3qfrpqDbTzQERNudnqX/6TqVZ/9ybxywxCfEWskyO1L6ooaCJDMSa5mS3anIglpoaDVFig5/AQiDtCpw1GOMb+nOjJg3gayrOzdpmt20Bp14KFebRD7/S+z8c40SjwIp/wo4DWscGyWgL1Ak6I0QSnS+/eYOvTn2eaMB2eYubG3jZGzpRbqUFgLhaS+Lt7uiKSqDGwbl9R4cyiW0L4TYgNeq34C6l0cc1RDy690awDSJtOI87cRsh7ds2TwzalW8L9OepoIQLm1oMkJzulBJU9Sriymtf9BAf9O8xxaNwSJp+oItVpC2jsW1fR/NFprAnqoGU3LXgefVGlCsw9Lg+SsFITPXvbNJwutdHUReyAyde/oesxfeFaFFWRQz1gzy+qmG4d/AJ5oQX2fU2l3tSNU0Q34M7IADdkpVYeM8oUP+szkSQHjBtGFpmdi4ZXOUXlABwGJT2UMdDFGP5EK1zJ8u+v4RwHjYWWK19eCqT3pytG+XQ0gobC54l+B2RkFqWtPLLP56iFd2cUBFt8DGTPeDonX4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
